#!/usr/bin/env python3

import sys

datapoints = [
    ('  Absolute upper-left X:  ', '-x'),
    ('  Absolute upper-left Y:  ', '-y'),
    ('  Width: ', '-w'),
    ('  Height: ', '-h')
]

for line in sys.stdin:
    line = line.rstrip()
    for key, opt in datapoints:
        if line.startswith(key):
            value = line[len(key):]
            print('{0} {1} '.format(opt, value), end='')

print()
