10 COLOR 15, 0
20 CLS
CALL DELAY (150000)
30 PRINT "lemmingelemmingelemminge"
40 CALL DELAY (150000)
50 CLS
60 PRINT " lemmingelemmingelemming"
70 PRINT "                        e"
80 CALL DELAY (150000)
90 CLS
100 PRINT "  lemmingelemmingelemmin"
110 PRINT "                        g"
120 PRINT "                        e"
130 CALL DELAY (150000)
140 CLS
150 PRINT "   lemmingelemmingelemmi"
160 PRINT "                        n"
170 PRINT "                        g"
180 PRINT "                        e"
190 CALL DELAY (150000)
200 CLS
210 PRINT "    lemmingelemmingelemm"
220 PRINT "                        i"
230 PRINT "                        n"
240 PRINT "                        g"
250 PRINT "                        e"
260 CALL DELAY (150000)
270 CLS
280 PRINT "     lemmingelemmingelem"
290 PRINT "                        m"
300 PRINT "                        i"
310 PRINT "                        n"
320 PRINT "                        g"
330 PRINT "                        e"
340 CALL DELAY (150000)
350 CLS
360 PRINT "      lemmingelemmingele"
370 PRINT "                        m"
380 PRINT "                        m"
390 PRINT "                        i"
400 PRINT "                        n"
410 PRINT "                        g"
420 PRINT "                         e"
430 CALL DELAY (150000)
440 CLS
450 PRINT "       lemmingelemmingel"
460 PRINT "                        e"
470 PRINT "                        m"
480 PRINT "                        m"
490 PRINT "                        i"
500 PRINT "                        n"
510 PRINT "                         ge"
520 CALL DELAY (150000)
530 CLS
540 PRINT "        lemmingelemminge"
550 PRINT "                        l"
560 PRINT "                        e"
570 PRINT "                        m"
580 PRINT "                        m"
590 PRINT "                        i"
600 PRINT "                         nge"
610 CALL DELAY (150000)
620 CLS
630 PRINT "         lemmingelemming"
640 PRINT "                        e"
650 PRINT "                        l"
660 PRINT "                        e"
670 PRINT "                        m"
680 PRINT "                        m"
690 PRINT "                         inge"
700 CALL DELAY (150000)
710 CLS
720 PRINT "          lemmingelemmin"
730 PRINT "                        g"
740 PRINT "                        e"
750 PRINT "                        l"
760 PRINT "                        e"
770 PRINT "                        m"
780 PRINT "                         minge"
790 CALL DELAY (150000)
800 CLS
810 PRINT "           lemmingelemmi"
820 PRINT "                        n"
830 PRINT "                        g"
840 PRINT "                        e"
850 PRINT "                        l"
860 PRINT "                        e"
870 PRINT "                         mminge"
880 CALL DELAY (150000)
890 CLS
900 PRINT "            lemmingelemm"
910 PRINT "                        i"
920 PRINT "                        n"
930 PRINT "                        g"
940 PRINT "                        e"
950 PRINT "                        l"
960 PRINT "                         emminge"
970 CALL DELAY (150000)
980 CLS
990 PRINT "             lemmingelem"
1000 PRINT "                        m"
1010 PRINT "                        i"
1020 PRINT "                        n"
1030 PRINT "                        g"
1040 PRINT "                        e"
1050 PRINT "                         lemminge"
1060 CALL DELAY (150000)
1070 CLS
1080 PRINT "              lemmingele"
1090 PRINT "                        m"
1100 PRINT "                        m"
1110 PRINT "                        i"
1120 PRINT "                        n"
1130 PRINT "                        g"
1140 PRINT "                         elemminge"
1150 CALL DELAY (150000)
1160 CLS
1170 PRINT "               lemmingel"
1180 PRINT "                        e"
1190 PRINT "                        m"
1200 PRINT "                        m"
1210 PRINT "                        i"
1220 PRINT "                        n         e"
1230 PRINT "                         gelemming"
1240 CALL DELAY (150000)
1250 CLS
1260 PRINT "                lemminge"
1270 PRINT "                        l"
1280 PRINT "                        e"
1290 PRINT "                        m"
1300 PRINT "                        m         e"
1310 PRINT "                        i         g"
1320 PRINT "                         ngelemmin"
1330 CALL DELAY (150000)
1340 CLS
1350 PRINT "                 lemming"
1360 PRINT "                        e"
1370 PRINT "                        l"
1380 PRINT "                        e         e"
1390 PRINT "                        m         g"
1400 PRINT "                        m         n"
1410 PRINT "                         ingelemmi"
1420 CALL DELAY (150000)
1430 CLS
1440 PRINT "                  lemmin"
1450 PRINT "                        g"
1460 PRINT "                        e         e"
1470 PRINT "                        l         g"
1480 PRINT "                        e         n"
1490 PRINT "                        m         i"
1500 PRINT "                         mingelemm"
1510 CALL DELAY (150000)
1520 CLS
1530 PRINT "                   lemmi"
1540 PRINT "                        n         e"
1550 PRINT "                        g         g"
1560 PRINT "                        e         n"
1570 PRINT "                        l         i"
1580 PRINT "                        e         m"
1590 PRINT "                         mmingelem"
1600 CALL DELAY (150000)
1610 CLS
1620 PRINT "                   lemm            e"
1630 PRINT "                        i         g"
1640 PRINT "                        n         n"
1650 PRINT "                        g         i"
1660 PRINT "                        e         m"
1670 PRINT "                        l         m"
1680 PRINT "                         emmingele"
1685 CALL DELAY (150000)
1687 CLS
1690 PRINT "                     lem           ge"
1700 PRINT "                        m         n"
1710 PRINT "                        i         i"
1720 PRINT "                        n         m"
1730 PRINT "                        g         m"
1740 PRINT "                        e         e"
1750 PRINT "                         lemmingel"
1760 CALL DELAY (150000)
1770 CLS
1780 PRINT "                      le           nge"
1790 PRINT "                        m         i"
1800 PRINT "                        m         m"
1810 PRINT "                        i         m"
1820 PRINT "                        n         e"
1830 PRINT "                        g         l"
1840 PRINT "                         elemminge"
1850 CALL DELAY (150000)
1860 CLS
1870 PRINT "                       l           inge"
1880 PRINT "                        e         m"
1890 PRINT "                        m         m"
1900 PRINT "                        m         e"
1910 PRINT "                        i         l"
1920 PRINT "                        n         e"
1930 PRINT "                         gelemming"
1940 CALL DELAY (150000)
1950 CLS
1960 PRINT "                                   minge"
1970 PRINT "                        l         m"
1980 PRINT "                        e         e"
1990 PRINT "                        m         l"
2000 PRINT "                        m         e"
2010 PRINT "                        i         g"
2020 PRINT "                         ngelemmin"
2030 CALL DELAY (150000)
2040 CLS
2050 PRINT "                                   mminge"
2060 PRINT "                                  e"
2070 PRINT "                        l         l"
2080 PRINT "                        e         e"
2090 PRINT "                        m         g"
2100 PRINT "                        m         n"
2110 PRINT "                         ingelemmi"
2120 CALL DELAY (150000)
2130 CLS
2140 PRINT "                                   emminge"
2150 PRINT "                                  l"
2160 PRINT "                                  e"
2170 PRINT "                        l         g"
2180 PRINT "                        e         n"
2190 PRINT "                        m         i"
2200 PRINT "                         mingelemm"
2210 CALL DELAY (150000)
2220 CLS
2230 PRINT "                                   lemminge"
2240 PRINT "                                  e"
2250 PRINT "                                  g"
2260 PRINT "                                  n"
2270 PRINT "                        l         i"
2280 PRINT "                        e         m"
2290 PRINT "                         mmingelem"
2300 CALL DELAY (150000)
2310 CLS
2320 PRINT "                                   elemminge"
2330 PRINT "                                  g"
2340 PRINT "                                  n"
2350 PRINT "                                  i"
2360 PRINT "                                  m"
2370 PRINT "                        l         m"
2380 PRINT "                         emmingele"
2390 CALL DELAY (150000)
2400 CLS
2410 PRINT "                                   gelemminge"
2420 PRINT "                                  n"
2430 PRINT "                                  i"
2440 PRINT "                                  m"
2450 PRINT "                                  m"
2460 PRINT "                                  e"
2470 PRINT "                         lemmingel"
2480 CALL DELAY (150000)
2490 CLS
2500 PRINT "                                   ngelemminge"
2510 PRINT "                                  i"
2520 PRINT "                                  m"
2530 PRINT "                                  m"
2540 PRINT "                                  e"
2550 PRINT "                                  l"
2560 PRINT "                          lemminge"
2570 CALL DELAY (150000)
2580 CLS
2590 PRINT "                                   ingelemminge"
2600 PRINT "                                  m"
2610 PRINT "                                  m"
2620 PRINT "                                  e"
2630 PRINT "                                  l"
2640 PRINT "                                  e"
2650 PRINT "                           lemming"
2660 CALL DELAY (150000)
2670 CLS
2680 PRINT "                                   mingelemminge"
2690 PRINT "                                  m"
2700 PRINT "                                  e"
2710 PRINT "                                  l"
2720 PRINT "                                  e"
2730 PRINT "                                  g"
2740 PRINT "                            lemmin"
2750 CALL DELAY (150000)
2760 CLS
2770 PRINT "                                   mmingelemminge"
2780 PRINT "                                  e"
2790 PRINT "                                  l"
2800 PRINT "                                  e"
2810 PRINT "                                  g"
2820 PRINT "                                  n"
2830 PRINT "                             lemmi"
2840 CALL DELAY (150000)
2850 CLS
2860 PRINT "                                   emmingelemminge"
2870 PRINT "                                  l"
2880 PRINT "                                  e"
2890 PRINT "                                  g"
2900 PRINT "                                  n"
2910 PRINT "                                  i"
2920 PRINT "                              lemm"
2930 CALL DELAY (150000)
2940 CLS
2950 PRINT "                                   lemmingelemminge"
2960 PRINT "                                  e"
2970 PRINT "                                  g"
2980 PRINT "                                  n"
2990 PRINT "                                  i"
3000 PRINT "                                  m"
3010 PRINT "                               lem"
3020 CALL DELAY (150000)
3030 CLS
3040 PRINT "                                   elemmingelemminge"
3050 PRINT "                                  g"
3060 PRINT "                                  n"
3070 PRINT "                                  i"
3080 PRINT "                                  m"
3090 PRINT "                                  m"
3100 PRINT "                                le"
3110 CALL DELAY (150000)
3120 CLS
3130 PRINT "                                   gelemmingelemminge"
3140 PRINT "                                  n"
3150 PRINT "                                  i"
3160 PRINT "                                  m"
3170 PRINT "                                  m"
3180 PRINT "                                  e"
3190 PRINT "                                 l"
3200 CALL DELAY (150000)
3210 CLS
3220 PRINT "                                   ngelemmingelemminge"
3230 PRINT "                                  i"
3240 PRINT "                                  m"
3250 PRINT "                                  m"
3260 PRINT "                                  e"
3270 PRINT "                                  l"
3280 CALL DELAY (150000)
3290 CLS
3300 PRINT "                                   ingelemmingelemminge"
3310 PRINT "                                  m"
3320 PRINT "                                  m"
3330 PRINT "                                  e"
3340 PRINT "                                  l"
3350 CALL DELAY (150000)
3360 CLS
3370 PRINT "                                   mingelemmingelemminge"
3380 PRINT "                                  m"
3390 PRINT "                                  e"
3400 PRINT "                                  l"
3410 CALL DELAY (150000)
3420 CLS
3430 PRINT "                                   mmingelemmingelemminge"
3440 PRINT "                                  e"
3450 PRINT "                                  l"
3460 CALL DELAY (150000)
3470 CLS
3480 PRINT "                                   emmingelemmingelemminge"
3490 PRINT "                                  l"
3500 CALL DELAY (150000)
3510 CLS
3520 PRINT "                                   lemmingelemmingelemminge"
3530 CALL DELAY (150000)
3540 CLS
3550 PRINT "                                    lemmingelemmingelemminge"
3560 CALL DELAY (150000)
3570 CLS
3580 PRINT "                                     lemmingelemmingelemminge"
3590 CALL DELAY (150000)
3600 CLS
3610 PRINT "                                      lemmingelemmingelemminge"
3620 CALL DELAY (150000)
3630 CLS
3640 PRINT "                                       lemmingelemmingelemminge"
3650 CALL DELAY (150000)
3660 CLS
3670 PRINT "                                        lemmingelemmingelemminge"
3680 CALL DELAY (150000)
3690 CLS
3700 PRINT "                                         lemmingelemmingelemminge"
3710 CALL DELAY (150000)
3720 CLS
3730 PRINT "                                          lemmingelemmingelemminge"
3740 CALL DELAY (150000)
3750 CLS
3760 PRINT "                                           lemmingelemmingelemminge"
3770 CALL DELAY (150000)
3780 CLS
3790 PRINT "                                            lemmingelemmingelemminge"
3800 CALL DELAY (150000)
3810 CLS
3820 PRINT "                                             lemmingelemmingelemminge"
3830 CALL DELAY (150000)
3840 CLS
3850 PRINT "                                              lemmingelemmingelemminge"
3860 CALL DELAY (150000)
3870 CLS
3880 PRINT "                                               lemmingelemmingelemminge"
3890 CALL DELAY (150000)
3900 CLS
3910 PRINT "                                                lemmingelemmingelemminge"
3920 CALL DELAY (150000)
3930 CLS
3940 PRINT "                                                 lemmingelemmingelemminge"
3950 CALL DELAY (150000)
3960 CLS
3970 PRINT "                                                  lemmingelemmingelemminge"
3980 CALL DELAY (150000)
3990 CLS
4000 PRINT "                                                   lemmingelemmingelemminge"
4010 CALL DELAY (150000)
4020 CLS
4030 PRINT "                                                    lemmingelemmingelemminge"
4040 CALL DELAY (150000)
4050 CLS
4060 PRINT "                                                     lemmingelemmingelemminge"
4070 CALL DELAY (150000)
4080 CLS
4090 PRINT "                                                      lemmingelemmingelemminge"
4100 CALL DELAY (150000)
4120 CLS
4130 PRINT "                                                       lemmingelemmingelemming"
4140 CALL DELAY (150000)
4150 CLS
4160 PRINT "                                                        lemmingelemmingelemmin"
4170 CALL DELAY (150000)
4180 CLS
4190 PRINT "                                                         lemmingelemmingelemmi"
4200 CALL DELAY (150000)
4210 CLS
4220 PRINT "                                                          lemmingelemmingelemm"
4230 CALL DELAY (150000)
4240 CLS
4250 PRINT "                                                           lemmingelemmingelem"
4260 CALL DELAY (150000)
4270 CLS
4280 PRINT "                                                            lemmingelemmingele"
4290 CALL DELAY (150000)
4300 CLS
4310 PRINT "                                                             lemmingelemmingel"
4320 CALL DELAY (150000)
4330 CLS
4340 PRINT "                                                              lemmingelemminge"
4350 CALL DELAY (150000)
4360 CLS
4370 PRINT "                                                               lemmingelemming"
4380 CALL DELAY (150000)
4390 CLS
4400 PRINT "                                                                lemmingelemmin"
4410 CALL DELAY (150000)
4420 CLS
4430 PRINT "                                                                 lemmingelemmi"
4440 CALL DELAY (150000)
4450 CLS
4460 PRINT "                                                                  lemmingelemm"
4470 CALL DELAY (150000)
4480 CLS
4490 PRINT "                                                                   lemmingelem"
4500 CALL DELAY (150000)
4510 CLS
4520 PRINT "                                                                    lemmingele"
4530 CALL DELAY (150000)
4540 CLS
4550 PRINT "                                                                     lemmingel"
4560 CALL DELAY (150000)
4570 CLS
4580 PRINT "                                                                      lemminge"
4590 CALL DELAY (150000)
4600 CLS
4610 PRINT "                                                                       lemming"
4620 CALL DELAY (150000)
4630 CLS
4640 PRINT "                                                                        lemmin"
4650 CALL DELAY (150000)
4660 CLS
4670 PRINT "                                                                         lemmi"
4680 CALL DELAY (150000)
4690 CLS
4700 PRINT "                                                                          lemm"
4710 CALL DELAY (150000)
4720 CLS
4730 PRINT "                                                                           lem"
4740 CALL DELAY (150000)
4750 CLS
4760 PRINT "                                                                            le"
4770 CALL DELAY (150000)
4780 CLS
4790 PRINT "                                                                             l"
4800 CALL DELAY (150000)
4810 CLS
CALL DELAY (1497005)
4830 COLOR 12
4840 PRINT "Das war:"
4850 PRINT "EBBE"
4860 PRINT "aus der Reihe"
4870 PRINT "LEMMIDEMMI"
4880 PRINT "von"
4890 PRINT "KILIAN EVANG"
4900 PRINT ""
4910 PRINT "Alle Rechte vorbehalten. (C) Kilian Evang 1998"
CALL DELAY (1497005)
4970 CLS
4980 PRINT "                        Weitere Folgen in Vorbereitung"
CALL DELAY (1497005)
5000 CLS
5010 COLOR 15
5020 END

SUB DELAY (steps)
FOR I = 1 TO steps
   FOR J = 1 TO 167: NEXT J
NEXT I
END SUB
