COLOR 15, 0
CLS
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
30 PRINT "lemmingelemmingelemminge"
40 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
50 CLS
60 PRINT "rlemmingelemmingelemming"
70 PRINT "                        e"
80 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
90 CLS
100 PRINT "erlemmingelemmingelemmin"
110 PRINT "                        g"
120 PRINT "                        e"
130 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
140 CLS
150 PRINT "terlemmingelemmingelemmi"
160 PRINT "                        n"
170 PRINT "                        g"
180 PRINT "                        e"
190 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
200 CLS
210 PRINT "iterlemmingelemmingelemm"
220 PRINT "                        i"
230 PRINT "                        n"
240 PRINT "                        g"
250 PRINT "                        e"
260 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
270 CLS
280 PRINT "eiterlemmingelemmingelem"
290 PRINT "                        m"
300 PRINT "                        i"
310 PRINT "                        n"
320 PRINT "                        g"
330 PRINT "                        e"
340 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
350 CLS
360 PRINT "seiterlemmingelemmingele"
370 PRINT "                        m"
380 PRINT "                        m"
390 PRINT "                        i"
400 PRINT "                        n"
410 PRINT "                        g"
420 PRINT "                        SPLASH!"
430 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
440 CLS
450 PRINT "nseiterlemmingelemmingel"
460 PRINT "                        e"
470 PRINT "                        m"
480 PRINT "                        m"
490 PRINT "                        i"
500 PRINT "                        n"
510 PRINT "                        PLUMPS!"
520 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
530 CLS
540 PRINT "enseiterlemmingelemminge"
550 PRINT "                        l"
560 PRINT "                        e"
570 PRINT "                        m"
580 PRINT "                        m"
590 PRINT "                        i"
600 PRINT "                        PLATSCH!"
610 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
620 CLS
630 PRINT "áenseiterlemmingelemming"
640 PRINT "                        e"
650 PRINT "                        l"
660 PRINT "                        e"
670 PRINT "                        m"
680 PRINT "                        m"
690 PRINT "                        BLUBB!"
700 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
710 CLS
720 PRINT "uáenseiterlemmingelemmin"
730 PRINT "                        g"
740 PRINT "                        e"
750 PRINT "                        l"
760 PRINT "                        e"
770 PRINT "                        m"
780 PRINT "                        GURGEL!"
790 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
800 CLS
810 PRINT "auáenseiterlemmingelemmi"
820 PRINT "                        n"
830 PRINT "                        g"
840 PRINT "                        e"
850 PRINT "                        l"
860 PRINT "                        e"
870 PRINT "                        BLUBBER!"
880 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
890 CLS
900 PRINT " auáenseiterlemmingelemm"
910 PRINT "                        i"
920 PRINT "                        n"
930 PRINT "                        g"
940 PRINT "                        e"
950 PRINT "                        l"
960 PRINT "                        SPODDER!"
970 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
980 CLS
990 PRINT "  auáenseiterlemmingelem"
1000 PRINT "                        m"
1010 PRINT "                        i"
1020 PRINT "                        n"
1030 PRINT "                        g"
1040 PRINT "                        e"
1050 PRINT "                        SPOTZ!"
1060 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1070 CLS
1080 PRINT "   auáenseiterlemmingele"
1090 PRINT "                        m"
1100 PRINT "                        m"
1110 PRINT "                        i"
1120 PRINT "                        n"
1130 PRINT "                        g"
1140 PRINT "                        SPLASH!"
1150 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1160 CLS
1170 PRINT "    auáenseiterlemmingel"
1180 PRINT "                        e"
1190 PRINT "                        m"
1200 PRINT "                        m"
1210 PRINT "                        i"
1220 PRINT "                        n"
1230 PRINT "                        BLUBB!"
1240 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1250 CLS
1260 PRINT "     auáenseiterlemminge"
1270 PRINT "                        l"
1280 PRINT "                        e"
1290 PRINT "                        m"
1300 PRINT "                        m"
1310 PRINT "                        i"
1320 PRINT "                        PLATSCH!"
1330 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1340 CLS
1350 PRINT "      auáenseiterlemming"
1360 PRINT "                        e"
1370 PRINT "                        l"
1380 PRINT "                        e"
1390 PRINT "                        m"
1400 PRINT "                        m"
1410 PRINT "                        ERTRINK!"
1420 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1430 CLS
1440 PRINT "       auáenseiterlemmin"
1450 PRINT "                        g"
1460 PRINT "                        e"
1470 PRINT "                        l"
1480 PRINT "                        e"
1490 PRINT "                        m"
1500 PRINT "                        SPLATSCH!"
1510 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1520 CLS
1530 PRINT "        auáenseiterlemmi"
1540 PRINT "                        n"
1550 PRINT "                        g"
1560 PRINT "                        e"
1570 PRINT "                        l"
1580 PRINT "                        e"
1590 PRINT "                        SHPLADDERWOSH!"
1600 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1610 CLS
1620 PRINT "         auáenseiterlemm"
1630 PRINT "                        i"
1640 PRINT "                        n"
1650 PRINT "                        g"
1660 PRINT "                        e"
1670 PRINT "                        l"
1680 PRINT "                        PLATSCH!"
1685 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1687 CLS
1690 PRINT "          auáenseiterlem"
1700 PRINT "                        m"
1710 PRINT "                        i"
1720 PRINT "                        n"
1730 PRINT "                        g"
1740 PRINT "                        e"
1750 PRINT "                        VERSINK!"
1760 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1770 CLS
1780 PRINT "           auáenseiterle"
1790 PRINT "                        m"
1800 PRINT "                        m"
1810 PRINT "                        i"
1820 PRINT "                        n"
1830 PRINT "                        g"
1840 PRINT "                        BLUBB!"
1850 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1860 CLS
1870 PRINT "            auáenseiterl"
1880 PRINT "                        e"
1890 PRINT "                        m"
1900 PRINT "                        m"
1910 PRINT "                        i"
1920 PRINT "                        n"
1930 PRINT "                        GURGEL!"
1940 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
1950 CLS
1960 PRINT "             auáenseiter"
1970 PRINT "                        l"
1980 PRINT "                        e"
1990 PRINT "                        m"
2000 PRINT "                        m"
2010 PRINT "                        i"
2020 PRINT "                        SPODDER!"
2030 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2040 CLS
2050 PRINT "             auáenseiter"
2060 PRINT ""
2070 PRINT "                        l"
2080 PRINT "                        e"
2090 PRINT "                        m"
2100 PRINT "                        m"
2110 PRINT "                        VERSINK!"
2120 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2130 CLS
2140 PRINT "             auáenseiter"
2150 PRINT ""
2160 PRINT ""
2170 PRINT "                        l"
2180 PRINT "                        e"
2190 PRINT "                        m"
2200 PRINT "                        SPLASH!"
2210 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2220 CLS
2230 PRINT "            auáenseiter"
2240 PRINT ""
2250 PRINT ""
2260 PRINT ""
2270 PRINT "                        l"
2280 PRINT "                        e"
2290 PRINT "                        PLADDERADATSCH!"
2300 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2310 CLS
2320 PRINT "           auáenseiter"
2330 PRINT ""
2340 PRINT ""
2350 PRINT ""
2360 PRINT ""
2370 PRINT "                        l"
2380 PRINT "                        BLUBBER!"
2390 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2400 CLS
2410 PRINT "          auáenseiter"
2420 PRINT ""
2430 PRINT ""
2440 PRINT ""
2450 PRINT ""
2460 PRINT ""
2470 PRINT "                        PLATSCH!"
2480 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2490 CLS
2500 PRINT "         auáenseiter"
2510 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2520 CLS
2530 PRINT "        auáenseiter"
2540 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2550 CLS
2560 PRINT "       auáenseiter"
2570 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2580 CLS
2590 PRINT "      auáenseiter"
2600 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2610 CLS
2620 PRINT "     auáenseiter"
2630 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2640 CLS
2650 PRINT "    auáenseiter"
2660 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2670 CLS
2680 PRINT "   auáenseiter"
2690 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2700 CLS
2710 PRINT "  auáenseiter"
2720 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2730 CLS
2740 PRINT " auáenseiter"
2750 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2760 CLS
2770 PRINT "auáenseiter"
2780 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2790 CLS
2800 PRINT "uáenseiter"
2810 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2820 CLS
2830 PRINT "áenseiter"
2840 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2850 CLS
2860 PRINT "enseiter"
2870 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2880 CLS
2890 PRINT "nseiter"
2900 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2910 CLS
2920 PRINT "seiter"
2930 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2940 CLS
2950 PRINT "eiter"
2960 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
2970 CLS
2980 PRINT "iter"
2990 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
3000 CLS
3010 PRINT "ter"
3020 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
3030 CLS
3040 PRINT "er"
3050 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
3060 CLS
3070 PRINT "r"
3080 FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 5000000: NEXT i
3090 CLS
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
3105 COLOR 12
3110 PRINT "Das war:"
3120 PRINT "DER AUSSENSEITER"
3130 PRINT "aus der Reihe"
3140 PRINT "LEMMIDEMMI"
3150 PRINT "von"
3160 PRINT "KILIAN EVANG"
3165 PRINT ""
3170 PRINT "Alle Rechte vorbehalten. (C) Kilian Evang 1998"
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
3230 CLS
3240 PRINT "                        Weitere Folgen in Vorbereitung"
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
FOR i = 1 TO 10000000: NEXT i
3260 CLS
3270 COLOR 15
3280 END

