10 COLOR 15, 0
20 CLS
25 CALL DELAY (150000)
30 PRINT "lemmingelemmingelemminge"
40 CALL DELAY (150000)
50 CLS
60 PRINT " lemmingelemmingelemming"
70 PRINT "                        e"
80 CALL DELAY (150000)
90 CLS
100 PRINT "  lemmingelemmingelemmin"
110 PRINT "                        g"
120 PRINT "                        e"
130 CALL DELAY (150000)
140 CLS
150 PRINT "   lemmingelemmingelemmi"
160 PRINT "                        n"
170 PRINT "                        g"
180 PRINT "                        e"
190 CALL DELAY (150000)
200 CLS
210 PRINT "    lemmingelemmingelemm"
220 PRINT "                        i"
230 PRINT "                        n"
240 PRINT "                        g"
250 PRINT "                        e"
260 CALL DELAY (150000)
270 CLS
280 PRINT "     lemmingelemmingelem"
290 PRINT "                        m"
300 PRINT "                        i"
310 PRINT "                        n"
320 PRINT "                        g"
330 PRINT "                        e"
340 CALL DELAY (150000)
350 CLS
360 PRINT "      lemmingelemmingele"
370 PRINT "                        m"
380 PRINT "                        m"
390 PRINT "                        i"
400 PRINT "                        n"
410 PRINT "                        g"
420 PRINT "                        SPLASH!"
430 CALL DELAY (150000)
440 CLS
450 PRINT "       lemmingelemmingel"
460 PRINT "                        e"
470 PRINT "                        m"
480 PRINT "                        m"
490 PRINT "                        i"
500 PRINT "                        n"
510 PRINT "                        PLUMPS!"
520 CALL DELAY (150000)
530 CLS
540 PRINT "        lemmingelemminge"
550 PRINT "                        l"
560 PRINT "                        e"
570 PRINT "                        m"
580 PRINT "                        m"
590 PRINT "                        i"
600 PRINT "                        PLATSCH!"
610 CALL DELAY (150000)
620 CLS
630 PRINT "         lemmingelemming"
640 PRINT "                        e"
650 PRINT "                        l"
660 PRINT "                        e"
670 PRINT "                        m"
680 PRINT "                        m"
690 PRINT "                        BLUBB!"
700 CALL DELAY (150000)
710 CLS
720 PRINT "          lemmingelemmin"
730 PRINT "                        g"
740 PRINT "                        e"
750 PRINT "                        l"
760 PRINT "                        e"
770 PRINT "                        m"
780 PRINT "                        GURGEL!"
790 CALL DELAY (150000)
800 CLS
810 PRINT "           lemmingelemmi"
820 PRINT "                        n"
830 PRINT "                        g"
840 PRINT "                        e"
850 PRINT "                        l"
860 PRINT "                        e"
870 PRINT "                        BLUBBER!"
880 CALL DELAY (150000)
890 CLS
900 PRINT "            lemmingelemm"
910 PRINT "                        i"
920 PRINT "                        n"
930 PRINT "                        g"
940 PRINT "                        e"
950 PRINT "                        l"
960 PRINT "                        SPODDER!"
970 CALL DELAY (150000)
980 CLS
990 PRINT "             lemmingelem"
1000 PRINT "                        m"
1010 PRINT "                        i"
1020 PRINT "                        n"
1030 PRINT "                        g"
1040 PRINT "                        e"
1050 PRINT "                        SPOTZ!"
1060 CALL DELAY (150000)
1070 CLS
1080 PRINT "              lemmingele"
1090 PRINT "                        m"
1100 PRINT "                        m"
1110 PRINT "                        i"
1120 PRINT "                        n"
1130 PRINT "                        g"
1140 PRINT "                        SPLASH!"
1150 CALL DELAY (150000)
1160 CLS
1170 PRINT "               lemmingel"
1180 PRINT "                        e"
1190 PRINT "                        m"
1200 PRINT "                        m"
1210 PRINT "                        i"
1220 PRINT "                        n"
1230 PRINT "                        BLUBB!"
1240 CALL DELAY (150000)
1250 CLS
1260 PRINT "                lemminge"
1270 PRINT "                        l"
1280 PRINT "                        e"
1290 PRINT "                        m"
1300 PRINT "                        m"
1310 PRINT "                        i"
1320 PRINT "                        PLATSCH!"
1330 CALL DELAY (150000)
1340 CLS
1350 PRINT "                 lemming"
1360 PRINT "                        e"
1370 PRINT "                        l"
1380 PRINT "                        e"
1390 PRINT "                        m"
1400 PRINT "                        m"
1410 PRINT "                        ERTRINK!"
1420 CALL DELAY (150000)
1430 CLS
1440 PRINT "                  lemmin"
1450 PRINT "                        g"
1460 PRINT "                        e"
1470 PRINT "                        l"
1480 PRINT "                        e"
1490 PRINT "                        m"
1500 PRINT "                        SPLATSCH!"
1510 CALL DELAY (150000)
1520 CLS
1530 PRINT "                   lemmi"
1540 PRINT "                        n"
1550 PRINT "                        g"
1560 PRINT "                        e"
1570 PRINT "                        l"
1580 PRINT "                        e"
1590 PRINT "                        SHPLADDERWOSH!"
1600 CALL DELAY (150000)
1610 CLS
1620 PRINT "                   lemm"
1630 PRINT "                        i"
1640 PRINT "                        n"
1650 PRINT "                        g"
1660 PRINT "                        e"
1670 PRINT "                        l"
1680 PRINT "                        PLATSCH!"
1685 CALL DELAY (150000)
1687 CLS
1690 PRINT "                     lem"
1700 PRINT "                        m"
1710 PRINT "                        i"
1720 PRINT "                        n"
1730 PRINT "                        g"
1740 PRINT "                        e"
1750 PRINT "                        VERSINK!"
1760 CALL DELAY (150000)
1770 CLS
1780 PRINT "                      le"
1790 PRINT "                        m"
1800 PRINT "                        m"
1810 PRINT "                        i"
1820 PRINT "                        n"
1830 PRINT "                        g"
1840 PRINT "                        BLUBB!"
1850 CALL DELAY (150000)
1860 CLS
1870 PRINT "                       l"
1880 PRINT "                        e"
1890 PRINT "                        m"
1900 PRINT "                        m"
1910 PRINT "                        i"
1920 PRINT "                        n"
1930 PRINT "                        GURGEL!"
1940 CALL DELAY (150000)
1950 CLS
1960 PRINT "                        "
1970 PRINT "                        l"
1980 PRINT "                        e"
1990 PRINT "                        m"
2000 PRINT "                        m"
2010 PRINT "                        i"
2020 PRINT "                        SPODDER!"
2030 CALL DELAY (150000)
2040 CLS
2050 PRINT "                        "
2060 PRINT ""
2070 PRINT "                        l"
2080 PRINT "                        e"
2090 PRINT "                        m"
2100 PRINT "                        m"
2110 PRINT "                        VERSINK!"
2120 CALL DELAY (150000)
2130 CLS
2140 PRINT "                        "
2150 PRINT ""
2160 PRINT ""
2170 PRINT "                        l"
2180 PRINT "                        e"
2190 PRINT "                        m"
2200 PRINT "                        SPLASH!"
2210 CALL DELAY (150000)
2220 CLS
2230 PRINT "                       "
2240 PRINT ""
2250 PRINT ""
2260 PRINT ""
2270 PRINT "                        l"
2280 PRINT "                        e"
2290 PRINT "                        PLADDERADATSCH!"
2300 CALL DELAY (150000)
2310 CLS
2320 PRINT "                      "
2330 PRINT ""
2340 PRINT ""
2350 PRINT ""
2360 PRINT ""
2370 PRINT "                        l"
2380 PRINT "                        BLUBBER!"
2390 CALL DELAY (150000)
2400 CLS
2410 PRINT "          "
2420 PRINT ""
2430 PRINT ""
2440 PRINT ""
2450 PRINT ""
2460 PRINT ""
2470 PRINT "                        PLATSCH!"
2480 CALL DELAY (150000)
2490 CLS
2500 CALL DELAY (500000)
2510 PRINT "L"
2520 CALL DELAY (75000)
2530 CLS
2540 PRINT " L"
2550 CALL DELAY (75000)
2560 CLS
2570 PRINT "  L"
2580 CALL DELAY (75000)
2590 CLS
2600 PRINT "   L"
2610 CALL DELAY (75000)
2620 CLS
2630 PRINT "    L"
2640 CALL DELAY (75000)
2650 CLS
2660 PRINT "     L"
2670 CALL DELAY (75000)
2680 CLS
2690 PRINT "      L"
2700 CALL DELAY (75000)
2710 CLS
2720 PRINT "       L"
2730 CALL DELAY (75000)
2740 CLS
2750 PRINT "        L"
2760 CALL DELAY (75000)
2770 CLS
2780 PRINT "         L"
2790 CALL DELAY (75000)
2800 CLS
2810 PRINT "          L"
2820 CALL DELAY (75000)
2830 CLS
2840 PRINT "           L"
2850 CALL DELAY (75000)
2860 CLS
2870 PRINT "            L"
2880 CALL DELAY (75000)
2890 CLS
2900 PRINT "             L"
2910 CALL DELAY (75000)
2920 CLS
2930 PRINT "              L"
2940 CALL DELAY (75000)
2950 CLS
2960 PRINT "               L"
2970 CALL DELAY (75000)
2980 CLS
2990 PRINT "                L"
3000 CALL DELAY (75000)
3010 CLS
3020 PRINT "                 L"
3030 CALL DELAY (75000)
3040 CLS
3050 PRINT "                  L"
3060 CALL DELAY (75000)
3070 CLS
3080 PRINT "                   L"
3090 CALL DELAY (75000)
3100 CLS
3110 PRINT "                    L"
3120 CALL DELAY (75000)
3130 CLS
3140 PRINT "                     L"
3150 CALL DELAY (75000)
3160 CLS
3170 PRINT "                      L"
3180 CALL DELAY (75000)
3190 CLS
3200 PRINT "                       L"
3210 CALL DELAY (75000)
3220 CLS
3230 PRINT ""
3235 PRINT "                        L"
3240 CALL DELAY (75000)
3250 CLS
3260 PRINT ""
3270 PRINT ""
3280 PRINT "                        L"
3290 CALL DELAY (75000)
3300 CLS
3310 PRINT ""
3320 PRINT ""
3330 PRINT ""
3340 PRINT "                        L"
3350 CALL DELAY (75000)
3360 CLS
3370 PRINT ""
3380 PRINT ""
3390 PRINT ""
3400 PRINT ""
3410 PRINT "                        L"
3420 CALL DELAY (75000)
3430 CLS
3440 PRINT ""
3450 PRINT ""
3460 PRINT ""
3470 PRINT ""
3480 PRINT ""
3490 PRINT "                        L"
3500 CALL DELAY (75000)
3510 CLS
3520 PRINT ""
3530 PRINT ""
3540 PRINT ""
3550 PRINT ""
3560 PRINT ""
3570 PRINT ""
3580 PRINT "                        SPLASH!"
3590 CALL DELAY (5000)
3600 COLOR 1
3610 GOSUB 4770
3620 COLOR 2
3630 GOSUB 4770
3640 COLOR 3
3650 GOSUB 4770
3660 COLOR 4
3670 GOSUB 4770
3680 COLOR 5
3690 GOSUB 4770
3700 COLOR 6
3710 GOSUB 4770
3720 COLOR 7
3730 GOSUB 4770
3740 COLOR 8
3750 GOSUB 4770
3760 COLOR 9
3770 GOSUB 4770
3780 COLOR 10
3790 GOSUB 4770
3800 COLOR 11
3810 GOSUB 4770
3820 COLOR 12
3830 GOSUB 4770
3840 COLOR 13
3850 GOSUB 4770
3860 COLOR 14
3870 GOSUB 4770
3880 COLOR 15
3890 GOSUB 4770
3900 PRINT ""
3910 PRINT ""
3920 PRINT ""
3930 PRINT ""
3940 PRINT ""
3950 PRINT "                          *"
3960 PRINT "                        SPLASH"
3970 CALL DELAY (75000)
3980 CLS
3985 COLOR 1
3990 PRINT ""
4000 PRINT ""
4010 PRINT ""
4020 PRINT ""
4030 PRINT "                        *  *"
4040 CALL DELAY (75000)
4050 CLS
4055 COLOR 2
4060 PRINT ""
4070 PRINT ""
4080 PRINT ""
4090 PRINT "                       *    *"
4100 CALL DELAY (75000)
4110 CLS
4115 COLOR 3
4120 PRINT ""
4130 PRINT ""
4140 PRINT "                      *      *"
4150 CALL DELAY (75000)
4160 CLS
4165 COLOR 4
4170 PRINT ""
4180 PRINT "                     *         *"
4190 CALL DELAY (75000)
4200 CLS
4205 COLOR 5
4210 PRINT ""
4220 PRINT ""
4230 PRINT "                    *           *"
4240 CALL DELAY (75000)
4250 CLS
4255 COLOR 6
4260 PRINT ""
4270 PRINT ""
4280 PRINT ""
4290 PRINT "                   *             *"
4300 CALL DELAY (75000)
4310 CLS
4315 COLOR 7
4320 PRINT ""
4330 PRINT ""
4340 PRINT ""
4350 PRINT ""
4360 PRINT "                    *           *"
4370 CALL DELAY (75000)
4380 CLS
4385 COLOR 8
4390 PRINT ""
4400 PRINT ""
4410 PRINT ""
4420 PRINT ""
4430 PRINT ""
4440 PRINT "                     *         *"
4450 CALL DELAY (75000)
4460 CLS
4465 COLOR 9
4470 PRINT ""
4480 PRINT ""
4490 PRINT ""
4500 PRINT ""
4510 PRINT ""
4520 PRINT ""
4530 PRINT "                      *       *"
4540 CALL DELAY (75000)
4550 CLS
4555 COLOR 10
4560 CALL DELAY (1497005)
4570 COLOR 12
4580 PRINT "Das war:"
4590 PRINT "DER NACHZšGLER"
4600 PRINT "aus der Reihe"
4610 PRINT "LEMMIDEMMI"
4620 PRINT "von"
4630 PRINT "KILIAN EVANG"
4640 PRINT ""
4650 PRINT "Alle Rechte vorbehalten. (C) Kilian Evang 1998"
4660 CALL DELAY (1497005)
4710 CLS
4720 PRINT "                        Weitere Folgen in Vorbereitung"
4730 CALL DELAY (1497005)
4740 CLS
4750 COLOR 15
4760 END
4770 CLS
4780 PRINT ""
4790 PRINT ""
4800 PRINT ""
4810 PRINT ""
4820 PRINT ""
4830 PRINT ""
4840 PRINT "                        SPLASH"
4845 CALL DELAY(50000)
4850 CLS
4860 RETURN

SUB DELAY (steps)
FOR I = 1 TO steps
   FOR J = 1 TO 167: NEXT J
NEXT I
END SUB
